{% set name = "dwave-hybrid" %}
{% set version = "0.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-hybrid-{{ version }}.tar.gz
  sha256: aa9f3278954e1795217d032c24f2b6d4d96e64ffc92981a273a11bc5d3bd2558

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-cloud-client >=0.10.6
    - click >5
    - dimod >=0.10.13,<0.13
    - dwave-greedy >=0.1.0
    - dwave-neal >=0.5.4
    - dwave-networkx >=0.8.8
    - dwave-preprocessing
    - dwave-system >=1.13.0
    - dwave-tabu >=0.2.0
    - minorminer >=0.1.7
    - networkx
    - numpy >=1.19.1
    - plucky >=0.4.3
    - python >=3.8

test:
  imports:
    - hybrid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-hybrid
  summary: Hybrid Asynchronous Decomposition Solver Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
