{% set name = "dwave-hybrid" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb5a7d7a780e53e59226c735ee5296f539e7cdc0863cd393cc177a2c02f1891e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-samplers >=1.0.0
    - dwave-cloud-client >=0.10.6
    - click >5
    - dimod >=0.12.2,<0.13
    - dwave-greedy >=0.1.0
    - dwave-neal >=0.5.4
    - dwave-networkx >=0.8.8
    - dwave-preprocessing >=0.5.4
    - dwave-system >=1.16.0
    - dwave-tabu >=0.2.0
    - minorminer >=0.1.7
    - networkx
    - numpy >=1.19.1
    - plucky >=0.4.3
    - python >=3.8

test:
  imports:
    - hybrid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-hybrid
  summary: Hybrid Asynchronous Decomposition Solver Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
